Changelogs
ufcg-lsd/asperathos pull request #6
Opened 2019-09-27 14:57 UTC by joseims

2019-09-30 12:58 UTC, matheuscmelo approved these changes

2019-09-30 14:37 UTC, liliarsampaio commented on CHANGELOG.md
> +- New plugin architecture for the following Asperathos components:
When adding a new feature, as a user, I would expect a little explanation on what the feature is about, especially in this case when a "new plugin arch" sounds so generic. Just saying something along the lines: "New plugin architecture that allows for the addition of custom plugins based on specific user needs..". Not too much detail, but at least we know what the change is about.

2019-09-30 14:38 UTC, liliarsampaio commented on CHANGELOG.md
> +- Persistent plugins for the following Asperathos components:
Rephrase to "Plugin persistence for the..."

2019-09-30 14:40 UTC, liliarsampaio commented on CHANGELOG.md
> +- PID scalling strategy at Asperathos Controller
Rephrase to "PID scaling strategy on the Controller component". Same as above, we know everything here is Asperathos related :)

2019-09-30 14:41 UTC, liliarsampaio commented on CHANGELOG.md
> +- New plugin architecture for the following Asperathos components:
Another thing is to remove "Asperathos" from the "Asperathos components" expression. Every change is related to Asperathos, no need to specify each time.

2019-09-30 14:45 UTC, liliarsampaio commented on CHANGELOG.md
> +- New tests for kubejobs plugin at Asperathos Monitor
Highlight ```kubejobs```. Rephrase to "New tests for the kubejobs plugin on the Monitor component."

2019-09-30 14:47 UTC, liliarsampaio commented on CHANGELOG.md
> +- Refactoring of the kubejobs plugin at Asperathos Manager
Highlight ```kubejobs```. Rephrase to "Refactoring of the kubejobs plugin of the Manager component."

2019-09-30 14:49 UTC, liliarsampaio commented on CHANGELOG.md
> +- Unused legacy plugins that were not working anymore
Never good to say something is "not working anymore" :) We should often say things are no longer supported, or not supported at the moment. That way, I would rephrase it to "... plugins that are not supported at the moment."

2019-09-30 14:49 UTC, liliarsampaio requested changes
some comments inline. thanks!

2019-10-14 18:14 UTC, matheuscmelo approved these changes

2020-04-02 17:28 UTC, merged